---
title: "Supplemental Tables for: Plant-derived benzoxazinoids act as antibiotics and shape bacterial communities"
author: "Niklas Schandry, Katharina Jandrasits, Ruben Garrido-Oter, Claude Becker"
output:
  pdf_document:
    toc: true
---

\newpage

```{r include=F, message=FALSE}
library(magrittr)
```

# Table S1. Syncom strains

```{r echo =F}
readr::read_rds("files_publication/syncom_membership.rds") %>% 
  dplyr::group_by(Syncom) %>% 
  dplyr::arrange(Genus) %>% 
  gt::gt() %>% 
  gt::as_latex()
```

\newpage

# Table S2. PERMANOVA

```{r echo=F}
readr::read_rds("files_publication/TabS2_permanova_gt.rds") %>% 
  gt::as_latex()
```

\newpage

# Table S3. PERMANOVA comparing only two treatments

```{r echo = F}
readr::read_rds("files_publication/TabS3_PERMANOVA_per_treatment_gt.rds") %>% 
  gt::as_latex()
```

\newpage

# Table S4. ANOVA: Observed taxa

```{r echo=F}
readr::read_rds("files_publication/TabS4_AOV_observed.rds") %>% 
  gt::as_latex()
```

\newpage

# Table S5. Observed diversity means and pairwise comparisons

```{r echo=F}
readr::read_rds("files_publication/TabS5_overserved_pairwise.rds")  %>% 
  gt::as_latex()
```

\newpage

# Table S6. ANOVA: Shannon Diversity

```{r echo=F}
readr::read_rds("files_publication/TabS6_AOV_shannon.rds") %>% 
  gt::as_latex()
```

\newpage

# Table S7. Shannon diversity means and pairwise comparisons

```{r echo=F}
readr::read_rds("files_publication/TabS7_shannon_pairwise.rds") %>% 
  gt::as_latex()
```

